title: Mohwa blog


baseurl: "/blog"

# Oveerriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true

permalink: pretty

# Conversion
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
lsi: false
excerpt_separator: "\n\n"

kramdown:
  auto_ids: true
  input: GFM
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

redcarpet:
    extensions:
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap


# redcarpet:
#    extensions: ["smart"]
gems: ['jekyll-lunr-js-search']

paginate: 10

author:
    twitter: yanione
    github: mohwa

# lunr serarch exclude file setup
#exclude_from_search: true
lunr_search:
  excludes: [rss.xml, atom.xml]